using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Paradise.SiliconComponents;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Systems;
using Content.Shared.FixedPoint;
using Content.Shared.Power.EntitySystems;
using Content.Shared.PowerCell;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Paradise.SiliconComponents.UI;

[GenerateTypedNameReferences]
public sealed partial class SiliconComponentsMenu : FancyWindow
{
    [Dependency] private IEntityManager _entity = default!;

    private PowerCellSystem _powerCell;
    private SharedBatterySystem _battery;
    private DamageableSystem _damageableSystem;

    public Action? OpticsButtonPressed;
    public Action? ServoButtonPressed;
    public Action? BrainButtonPressed;
    public Action? SpineButtonPressed;
    public Action? DriveButtonPressed;
    public Action? EjectBatteryButtonPressed;
    public Action<EntityUid>? RemoveModuleButtonPressed;

    private List<EntityUid> _modules = new();

    public EntityUid Entity;

    public readonly Dictionary<ProgressBar, PartType> IntegrityBarDict = new Dictionary<ProgressBar, PartType>();

    public SiliconComponentsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ButtonDict[PartType.Brain] = BrainButton;
        ButtonDict[PartType.Drive] = DriveButton;
        ButtonDict[PartType.Optics] = OpticsButton;
        ButtonDict[PartType.Spine] = SpineButton;
        ButtonDict[PartType.Servo] = ServoButton;

        _powerCell = _entity.System<PowerCellSystem>();
        _battery = _entity.System<SharedBatterySystem>();
        _damageableSystem = _entity.System<DamageableSystem>();

        EjectBatteryButton.OnPressed += _ => EjectBatteryButtonPressed?.Invoke();
        OpticsButton.OnPressed += _ => OpticsButtonPressed?.Invoke();
        ServoButton.OnPressed += _ => ServoButtonPressed?.Invoke();
        BrainButton.OnPressed += _ => BrainButtonPressed?.Invoke();
        SpineButton.OnPressed += _ => SpineButtonPressed?.Invoke();
        DriveButton.OnPressed += _ => DriveButtonPressed?.Invoke();

        OpticsButton.TexturePath = "/Textures/Interface/Minimalist/SlotBackground.png";
        ServoButton.TexturePath = "/Textures/Interface/Minimalist/SlotBackground.png";
        BrainButton.TexturePath = "/Textures/Interface/Minimalist/SlotBackground.png";
        SpineButton.TexturePath = "/Textures/Interface/Minimalist/SlotBackground.png";
        DriveButton.TexturePath = "/Textures/Interface/Minimalist/SlotBackground.png";

        IntegrityBarDict[IntegrityDisplayBarOptics] = PartType.Optics;
        IntegrityBarDict[IntegrityDisplayBarServo] = PartType.Servo;
        IntegrityBarDict[IntegrityDisplayBarSpine] = PartType.Spine;
        IntegrityBarDict[IntegrityDisplayBarDrive] = PartType.Drive;
    }

    public readonly Dictionary<PartType, TextureButton> ButtonDict = new Dictionary<PartType, TextureButton>();

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;

        BorgSprite.SetEntity(entity);

        UpdateBatteryButton();
        UpdateButtons();
        UpdateModulePanel();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        FixedPoint2 charge = 0f;

        FixedPoint2 chargeMax = 0f;

        FixedPoint2 chargeFraction = 0f;

        if (_powerCell.TryGetBatteryFromSlot(Entity, out var battery))
        {
            charge = _battery.GetCharge(battery.Value.AsNullable());
            chargeMax = battery.Value.Comp.MaxCharge;
            chargeFraction = charge / chargeMax;
        }

        BatteryCharge.Text = Loc.GetString("synth-battery-charge", ("amount", charge), ("percentage", chargeFraction * 100));
        BatteryCharge.FontColorOverride = Color.DarkGreen;
        BatteryChargeMax.Text = Loc.GetString("synth-battery-charge-max", ("amount", chargeMax));
        BatteryChargeMax.FontColorOverride = Color.DarkGreen;
    }

    public void UpdateBatteryButton()
    {
        EjectBatteryButton.Disabled = !_powerCell.HasBattery(Entity);
    }

    public void UpdateIntegrityBars()
    {
        if (!_entity.TryGetComponent(Entity, out SiliconComponentsComponent? comp))
            return;

        foreach (var bar in IntegrityBarDict.Keys)
        {
            FixedPoint2 partintegrityPercent;

            if (comp.Parts[IntegrityBarDict[bar]].ContainedEntity is not { Valid: true } partValidated ||
                !_entity.TryGetComponent<DamabeableSiliconPartComponent>(partValidated, out var partComp))
            {
                partintegrityPercent = 0;
                bar.Value = partintegrityPercent.Float();
                bar.Visible = false;
                continue;
            }

            var totalDamage = _damageableSystem.GetTotalDamage(partValidated);
            partintegrityPercent = FixedPoint2.Clamp(partComp.MaxDamageToRemainFunctional - totalDamage, 0, partComp.MaxDamageToRemainFunctional) / partComp.MaxDamageToRemainFunctional;
            bar.Value = partintegrityPercent.Float();

            if (!bar.Visible)
                bar.Visible = true;
        }
    }

    public void UpdateButtons()
    {
        if (!_entity.TryGetComponent(Entity, out SiliconComponentsComponent? comp))
            return;

        foreach (var button in ButtonDict.Keys)
        {
            SpriteView? buttonView = null;

            foreach (var child in ButtonDict[button].Children)
            {
                if (child is SpriteView childView)
                {
                    buttonView = childView;
                    break;
                }
            }

            if (buttonView == null)
                return;

            if (ButtonDict[button] == null)
                continue;

            if (comp.Parts.TryGetValue(button, out var part) && part.ContainedEntity is { Valid: true } partValid)
            {
                //ButtonDict[button].Text = _entity.GetComponent<MetaDataComponent>(partValid).EntityName;

                buttonView.SetEntity(partValid);
                buttonView.Visible = true;

                continue;
            }

            buttonView.Visible = false;
            ButtonDict[button].RemoveStyleClass(StyleClass.ButtonOpenLeft);
        }
    }

    public void UpdateModulePanel()
    {
        if (!_entity.TryGetComponent(Entity, out SiliconComponentsComponent? owner))
            return;

        ModuleCounter.Text = Loc.GetString("borg-ui-module-counter",
            ("actual", owner.ModuleSpace),
            ("max", owner.MaxModuleSpace));

        if (owner.ModuleContainer.Count == _modules.Count)
        {
            var isSame = true;
            foreach (var module in owner.ModuleContainer.ContainedEntities)
            {
                if (_modules.Contains(module))
                    continue;
                isSame = false;
                break;
            }

            if (isSame)
                return;
        }

        ModuleContainer.Children.Clear();
        _modules.Clear();
        foreach (var module in owner.ModuleContainer.ContainedEntities)
        {
            var moduleComponent = _entity.GetComponent<SiliconModuleComponent>(module);
            var control = new SiliconModuleControl(module, _entity, true);
            control.RemoveButtonPressed += () =>
            {
                RemoveModuleButtonPressed?.Invoke(module);
            };
            ModuleContainer.AddChild(control);
            _modules.Add(module);
        }
    }
}
